// Razorpay Configuration
const RAZORPAY_CONFIG = {
  // Live Key ID - Get from your Razorpay Dashboard
  key_id: process.env.REACT_APP_RAZORPAY_KEY_ID || 'rzp_live_RMcbXYH6jZlYF1',
  
  // Currency
  currency: 'INR',
  
  // Company details
  name: 'Varaha Silks',
  description: 'Premium Silk Sarees and Traditional Wear',
  
  // Theme
  theme: {
    color: '#3399cc'
  },
  
  // Prefill customer details
  prefill: {
    name: '',
    email: '',
    contact: ''
  },
  
  // Notes
  notes: {
    address: 'Varaha Silks Store'
  }
};

// Razorpay options for different payment methods
const getRazorpayOptions = (orderData, customerData) => {
  const amount = Math.round(orderData.amount * 100); // Convert to paise
  
  console.log('🔑 Razorpay Key ID:', RAZORPAY_CONFIG.key_id);
  console.log('💰 Amount (paise):', amount);
  
  return {
    key: RAZORPAY_CONFIG.key_id,
    amount: amount,
    currency: RAZORPAY_CONFIG.currency,
    name: RAZORPAY_CONFIG.name,
    description: `${RAZORPAY_CONFIG.description} - Order #${orderData.orderId}`,
    image: '/logo.png', // Your logo URL
    order_id: orderData.razorpayOrderId, // This will be generated by your backend
    prefill: {
      name: customerData.name,
      email: customerData.email,
      contact: customerData.phone
    },
    notes: {
      address: customerData.address,
      order_id: orderData.orderId
    },
    theme: RAZORPAY_CONFIG.theme,
    modal: {
      ondismiss: function() {
        console.log('Razorpay modal dismissed');
      }
    },
    timeout: 300, // 5 minutes timeout for payment completion
    retry: {
      enabled: true,
      max_count: 3
    }
  };
};

// Payment method configurations
const PAYMENT_METHODS = {
  RAZORPAY: 'razorpay',
  CARD: 'card',
  UPI: 'upi',
  NETBANKING: 'netbanking',
  WALLET: 'wallet'
};

// Supported payment methods
const SUPPORTED_PAYMENT_METHODS = [
  {
    id: PAYMENT_METHODS.RAZORPAY,
    name: 'Razorpay',
    description: 'Pay with Razorpay (Cards, UPI, Net Banking, Wallets)',
    icon: '💳',
    enabled: true
  },
  {
    id: 'test',
    name: 'Test Payment',
    description: 'Test payment method (bypasses Razorpay for debugging)',
    icon: '🧪',
    enabled: true
  }
];

module.exports = {
  RAZORPAY_CONFIG,
  getRazorpayOptions,
  PAYMENT_METHODS,
  SUPPORTED_PAYMENT_METHODS
};
